---
name: foundryvtt
services:
  foundryvtt:
    image: ghcr.io/felddy/foundryvtt:14
    container_name: foundryvtt
    hostname: foundryvtt

    environment:
      - TZ=America/Denver
      - FOUNDRY_USERNAME=${FOUNDRY_USERNAME}
      - FOUNDRY_PASSWORD=${FOUNDRY_PASSWORD}
      - FOUNDRY_ADMIN_KEY=${FOUNDRY_ADMIN_KEY}
      - CONTAINER_PRESERVE_CONFIG=true

    ports:
      - 30000:30000/tcp

    volumes:
      - /opt/digiur-net/foundryvtt/data:/data

    restart: unless-stopped
