---
name: librespeed
services:
  librespeed:
    image: lscr.io/linuxserver/librespeed
    container_name: librespeed

    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Denver
      PASSWORD: password

    volumes:
      - ./config:/config

    ports:
      - 81:80

    restart: unless-stopped