---
name: prowlarr
services:
  prowlarr:
    image: linuxserver/prowlarr
    cpu_shares: 1024
    container_name: prowlarr

    environment:
      PGID: 1000
      PUID: 1000
      TZ: America/Denver

    ports:
      - 9696:9696

    volumes:
      - ./config:/config

    restart: unless-stopped
