---
name: handbrake
services:
  handbrake:
    image: jlesage/handbrake
    container_name: handbrake

    environment:
      USER_ID: 1000

    devices:
      - /dev/dri:/dev/dri

    ports:
      - 5800:5800

    volumes:
      - ./config:/config
      - /storage:/storage

    restart: unless-stopped
