---
name: handbrake
services:
  handbrake:
    image: jlesage/handbrake
    container_name: handbrake

    environment:
      USER_ID: 1000
      AUTOMATED_CONVERSION_PRESET: "General/H.265 QSV 720p"
      AUTOMATED_CONVERSION_OUTPUT_SUBDIR: SAME_AS_SRC
      AUTOMATED_CONVERSION_FORMAT: m4v
      AUTOMATED_CONVERSION_NON_VIDEO_FILE_ACTION: copy
      AUTOMATED_CONVERSION_OVERWRITE_OUTPUT: 1
      AUTOMATED_CONVERSION_SOURCE_STABLE_TIME: 7

    devices:
      - /dev/dri:/dev/dri

    ports:
      - 5800:5800

    volumes:
      - ./config:/config
      - /storage/media:/output
      - /storage/media/downloads/raw:/watch
      - /storage:/storage

    restart: unless-stopped
