---
name: handbrake
services:
  handbrake:
    image: jlesage/handbrake
    container_name: handbrake

    ports:
      - 5800:5800

    volumes:
      - ./config:/config
      - /storage:/storage

    environment:
      USER_ID: 1000

    restart: unless-stopped
