---
name: myspeed
services:
  myspeed:
    image: germannewsmaker/myspeed
    cpu_shares: 1024
    container_name: myspeed

    ports:
      - 5216:5216

    volumes:
      - /opt/digiur-net/myspeed/data:/myspeed/data

    restart: unless-stopped
