---
name: memos
services:
  memos:
    image: neosmemo/memos
    container_name: memos

    environment:
      PGID: 1000
      PUID: 1000
      TZ: America/Denver

    ports:
      - 5230:5230

    volumes:
      - ./var/opt/memos:/var/opt/memos

    restart: unless-stopped
