---
name: qdirstat
services:
  qdirstat:
    image: lscr.io/linuxserver/qdirstat
    container_name: qdirstat

    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Denver

    ports:
      - 3000:3000

    volumes:
      - ./config:/config
      - /:/data:ro

    restart: unless-stopped