---
name: radarr
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    cpu_shares: 1024
    container_name: radarr

    environment:
      PGID: 1000
      PUID: 1000
      TZ: America/Denver

    ports:
      - 7878:7878

    volumes:
      - /opt/digiur-net/radarr/config:/config
      - /storage/downloads:/storage/downloads

    restart: unless-stopped
