---
name: sonarr
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr

    environment:
      PGID: 1000
      PUID: 1000
      TZ: America/Denver

    ports:
      - target: 8989
        published: "8989"
        protocol: tcp

    volumes:
      - ./config
      - /storage:/Storage

    restart: unless-stopped
