---
name: sonarr
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr

    environment:
      PGID: 1000
      PUID: 1000
      TZ: America/Denver

    ports:
      - 8989:8989

    volumes:
      - ./config
      - /storage:/Storage

    restart: unless-stopped
