---
name: navidrome
services:
  navidrome:
    image: deluan/navidrome
    container_name: navidrome

    environment:
      ND_SCANSCHEDULE: 0
      TZ: America/Denver

    ports:
      - 4533:4533

    volumes:
      - ./data:/data
      - /storage/music:/music

    restart: unless-stopped
