---
name: romm
volumes:
  romm_redis_data:
services:
  romm:
    image: rommapp/romm:latest
    cpu_shares: 1024
    container_name: romm
    depends_on:
      - romm-db

    environment:
      DB_HOST: romm-db
      DB_NAME: romm # Should match MYSQL_DATABASE in mariadb
      DB_USER: romm-user # Should match MYSQL_USER in mariadb
      DB_PASSWD: ${ROMM_DB_PASSWORD} # Should match MYSQL_PASSWORD in mariadb
      ROMM_AUTH_SECRET_KEY: ${ROMM_AUTH_SECRET_KEY}
      IGDB_CLIENT_ID: ${IGDB_CLIENT_ID}
      IGDB_CLIENT_SECRET: ${IGDB_CLIENT_SECRET}
      ENABLE_RESCAN_ON_FILESYSTEM_CHANGE: true
      TZ: America/Denver

    volumes:
      - ./romm/resources:/romm/resources # Resources fetched from IGDB (covers, screenshots, etc.)
      - romm_redis_data:/redis-data # Cached data for background tasks
      - /mnt/nas/roms:/romm/library # Your game library
      - ./romm/assets:/romm/assets # Uploaded saves, states, etc.
      - ./romm/config:/romm/config # Path where config.yml is stored

    ports:
      - 1337:8080

    restart: unless-stopped

  romm-db:
    image: mariadb:latest # if you experience issues, try: linuxserver/mariadb:latest
    cpu_shares: 1024
    container_name: romm-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${ROMM_DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=romm
      - MYSQL_USER=romm-user
      - MYSQL_PASSWORD=${ROMM_DB_PASSWORD}
    volumes:
      - ./var/lib/mysql:/var/lib/mysql
