---
name: romm
volumes:
  romm_redis_data:
  mysql_data:

services:
  romm:
    image: rommapp/romm:latest
    cpu_shares: 1024
    container_name: romm
    depends_on:
      romm-maria-db:
        condition: service_healthy

    environment:
      DB_HOST: romm-maria-db
      DB_NAME: romm # Should match MYSQL_DATABASE in mariadb
      DB_USER: romm-user # Should match MYSQL_USER in mariadb
      DB_PASSWD: ${ROMM_DB_PASSWORD} # Should match MYSQL_PASSWORD in mariadb
      ROMM_AUTH_SECRET_KEY: ${ROMM_AUTH_SECRET_KEY}
      HASHEOUS_API_ENABLED: "true"
      ENABLE_RESCAN_ON_FILESYSTEM_CHANGE: true
      TZ: America/Denver

    volumes:
      - /opt/digiur-net/romm/resources:/romm/resources # Metadata and artwork fetched by RomM
      - romm_redis_data:/redis-data # Cached data for background tasks
      - /mnt/nas/roms:/romm/library # Your game library
      - /opt/digiur-net/romm/assets:/romm/assets # Uploaded saves, states, etc.
      - /opt/digiur-net/romm/config:/romm/config # Path where config.yml is stored

    ports:
      - 1337:8080

    restart: unless-stopped

  romm-maria-db:
    image: lscr.io/linuxserver/mariadb:latest
    cpu_shares: 1024
    container_name: romm-maria-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${ROMM_DB_PASSWORD}
      - MYSQL_DATABASE=romm
      - MYSQL_USER=romm-user
      - MYSQL_PASSWORD=${ROMM_DB_PASSWORD}
    volumes:
      - mysql_data:/config
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "--host=127.0.0.1", "--silent"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5
