---
name: snapdrop
services:
  snapdrop:
    image: linuxserver/snapdrop
    container_name: snapdrop

    environment:
      PGID: 1000
      PUID: 1000
      TZ: America/Denver

    ports:
      - 89:80

    volumes:
      - ./config:/config

    restart: unless-stopped
