---
name: sonarr
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    cpu_shares: 1024
    container_name: sonarr

    environment:
      PGID: 1000
      PUID: 1000
      TZ: America/Denver

    ports:
      - 8989:8989

    volumes:
      - /opt/digiur-net/sonarr/config:/config
      - /storage/downloads:/storage/downloads

    restart: unless-stopped
