---
services:

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer

    ports:
      - 9000:9000

    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock

    environment:
      - UID=1000
      - GID=1000


    restart: always
