---
name: mealie
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie
    container_name: mealie

    environment:
      PUID: 1000
      GUID: 1000
      TZ: America/Denver
      BASE_URL: http://192.168.1.99

    ports:
      - 9925:9000

    volumes:
      - ./app/data:/app/data

    restart: unless-stopped
