---
name: jellyfin
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    cpu_shares: 2048

    environment:
      PGID: 1000
      PUID: 1000
      TZ: America/Denver
      JELLYFIN_PublishedServerUrl: ${JELLYFIN_PUBLISHED_SERVER_URL}

    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp

    volumes:
      - /opt/digiur-net/jellyfin/config:/config
      - /mnt/nas:/mnt/nas

    devices:
      # GPU device for hardware video transcoding (Intel/AMD VAAPI)
      - /dev/dri:/dev/dri

    restart: unless-stopped
