---
name: myspeed
services:
  myspeed:
    image: germannewsmaker/myspeed
    container_name: myspeed

    ports:
      - 5216:5216

    volumes:
      - ./myspeed/data:/myspeed/data

    restart: unless-stopped
