---
name: librespeed
services:
  librespeed:
    image: lscr.io/linuxserver/librespeed:latest
    cpu_shares: 1024
    container_name: librespeed

    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Denver
      PASSWORD: ${LIBRESPEED_PASSWORD}

    volumes:
      - /opt/digiur-net/librespeed/config:/config

    ports:
      - 81:80

    restart: unless-stopped