---
name: handbrake
services:
  handbrake:
    container_name: handbrake
    image: jlesage/handbrake
    cpu_shares: 512
    environment:
      USER_ID: 1000
      GROUP_ID: 1000
      AUTOMATED_CONVERSION: 0

    devices:
      - /dev/dri:/dev/dri

    ports:
      - 5800:5800

    volumes:
      - /opt/digiur-net/handbrake/config:/config
      - /storage:/storage:ro
      - /storage/downloads/processing:/watch
      - /mnt/nas:/output

    restart: unless-stopped
