---
name: mealie
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie
    cpu_shares: 1024
    container_name: mealie

    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Denver
      BASE_URL: ${MEALIE_BASE_URL}

    ports:
      - 9925:9000

    volumes:
      - /opt/digiur-net/mealie/data:/app/data

    restart: unless-stopped
