---
name: transmission-plus-gluten
services:
  transmissionplus:
    image: linuxserver/transmission
    container_name: transmissionplus

    network_mode: "service:gluetun"

    volumes:
      - ./transmission/config:/config
      - /DATA/Storage/Downloads:/DATA/Storage/Downloads

    environment:
      USER: digiur
      PASS: 733stsbytes
      PEERPORT: 60357
      PGID: 1000
      PUID: 1000
      TZ: America/Denver

    restart: unless-stopped

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun

    cap_add:
      - NET_ADMIN

    devices:
      - /dev/net/tun:/dev/net/tun

    ports:
      - 9001:9000/tcp
      - 9091:9091/tcp
      - 60357:60357/tcp
      - 60357:60357/udp

    volumes:
      - ./gluetun:/gluetun

    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=JGtxmAcnVk0cvZGp+pmp
      - OPENVPN_PASSWORD=7VymDvSipUDYNdqrd9uJPHsnAmywPAud
      - PORT_FORWARD_ONLY=on
      - VPN_PORT_FORWARDING=on
      - SERVER_COUNTRIES=Switzerland
      - TZ=America/Denver

    restart: always
