---
services:

  dashy:
    image: lissy93/dashy
    container_name: Dashy

    ports:
      - 80:8080





    environment:
      - UID=1000
      - GID=1000
      - NODE_ENV=production

    restart: unless-stopped
