---
services:
  dashy:
    image: lissy93/dashy
    container_name: Dashy
    volumes:
      - ./dashy/app/user-data/conf.yml:/app/user-data/conf.yml
    ports:
      - 80:8080
    environment:
      - NODE_ENV=production
      - UID=1000
      - GID=1000
    restart: unless-stopped
