---
name: uptime-kuma
services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma

    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Denver

    ports:
      - 3001:3001

    volumes:
      - ./app/data:/app/data

    restart: unless-stopped
