---
name: prowlarr
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    cpu_shares: 1024
    container_name: prowlarr

    environment:
      PGID: 1000
      PUID: 1000
      TZ: America/Denver

    ports:
      - 9696:9696

    volumes:
      - /opt/digiur-net/prowlarr/config:/config

    restart: unless-stopped
    depends_on:
      - flaresolverr

  # configure as an Indexer Proxy in Prowlarr at http://flaresolverr:8191.
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    cpu_shares: 512
    container_name: flaresolverr

    environment:
      LOG_LEVEL: info
      TZ: America/Denver

    restart: unless-stopped
